name: Python application

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/**'
      - 'requirements.txt'
    branches:
      - main
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/**'
      - 'requirements.txt'
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unittest
        pip install -r requirements.txt
    - name: Test with UnitTest
      run: |
        py tests/__init__.py